"""initial schema

Implements the schema in docs/DATA_MODEL.md exactly: reference tables
(accounts, tickers, trade_types, commissions), the immutable trades /
append-only trade_events tables, and the cash_flows / cost_basis /
bankroll ledger tables — plus the two derived views
(v_trade_current_status, v_cost_basis_running) as raw SQL, since
Alembic has no native construct for views.

Revision ID: d5e684ca66b6
Revises: 
Create Date: 2026-08-24 23:08:22.500293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e684ca66b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('needs_update', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('trade_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('is_credit', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requires_expiration', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requires_strike', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requires_contracts', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requires_shares', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('bankroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('trade_type_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Text(), nullable=False),
    sa.Column('trade_parent_id', sa.Integer(), nullable=True),
    sa.Column('date_trade_open', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('days_to_expiration', sa.Integer(), nullable=True),
    sa.Column('num_of_contracts', sa.Integer(), nullable=True),
    sa.Column('num_of_shares', sa.Integer(), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('long_strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('credit_debit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_per_share', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin_capital', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('net_credit_per_share', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('risk_capital_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('arorc', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('schwab_order_id', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['trade_parent_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['trade_type_id'], ['trade_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_account', 'trades', ['account_id'], unique=False)
    op.create_index('idx_trades_parent', 'trades', ['trade_parent_id'], unique=False)
    op.create_index('idx_trades_ticker', 'trades', ['ticker_id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_flows_trade', 'cash_flows', ['trade_id'], unique=False)
    op.create_table('trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('closing_debit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('schwab_order_id', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.CheckConstraint("event_type IN ('OPEN','ROLL','ADJUST','CLOSE','EXPIRE','ASSIGN')", name='ck_trade_events_event_type'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_events_trade', 'trade_events', ['trade_id'], unique=False)
    op.create_table('cost_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('cash_flow_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('cost_per_share', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cash_flow_id'], ['cash_flows.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_basis_ticker_account', 'cost_basis', ['account_id', 'ticker_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###

    # Views — Alembic doesn't manage these natively, so they're raw SQL.
    # See docs/DATA_MODEL.md §2 and §3 for the derivations these encode.
    op.execute("""
        CREATE VIEW v_trade_current_status AS
        SELECT
            t.id AS trade_id,
            t.account_id,
            t.ticker_id,
            CASE
                WHEN EXISTS (SELECT 1 FROM trade_events e WHERE e.trade_id = t.id AND e.event_type IN ('CLOSE','EXPIRE','ASSIGN'))
                THEN 'closed' ELSE 'open'
            END AS trade_status,
            (SELECT event_date FROM trade_events e WHERE e.trade_id = t.id AND e.event_type IN ('CLOSE','EXPIRE','ASSIGN') ORDER BY event_date DESC LIMIT 1) AS date_trade_closed,
            (SELECT closing_debit FROM trade_events e WHERE e.trade_id = t.id AND e.event_type IN ('CLOSE','EXPIRE','ASSIGN') ORDER BY event_date DESC LIMIT 1) AS closing_debit,
            (SELECT event_date FROM trade_events e WHERE e.trade_id = t.id AND e.event_type = 'ROLL' ORDER BY event_date DESC LIMIT 1) AS date_trade_rolled
        FROM trades t;
    """)

    op.execute("""
        CREATE VIEW v_cost_basis_running AS
        SELECT
            cb.*,
            SUM(cb.total_amount) OVER (
                PARTITION BY cb.account_id, cb.ticker_id ORDER BY cb.transaction_date, cb.id
            ) AS running_basis,
            SUM(cb.shares) OVER (
                PARTITION BY cb.account_id, cb.ticker_id ORDER BY cb.transaction_date, cb.id
            ) AS running_shares
        FROM cost_basis cb;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Views depend on the tables below, so they must go first.
    op.execute("DROP VIEW IF EXISTS v_cost_basis_running")
    op.execute("DROP VIEW IF EXISTS v_trade_current_status")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cost_basis_ticker_account', table_name='cost_basis')
    op.drop_table('cost_basis')
    op.drop_index('idx_trade_events_trade', table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index('idx_cash_flows_trade', table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index('idx_trades_ticker', table_name='trades')
    op.drop_index('idx_trades_parent', table_name='trades')
    op.drop_index('idx_trades_account', table_name='trades')
    op.drop_table('trades')
    op.drop_table('commissions')
    op.drop_table('bankroll')
    op.drop_table('trade_types')
    op.drop_table('tickers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
